# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: book.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
import book_pb2


class BookServiceBase(abc.ABC):

    @abc.abstractmethod
    async def BookCreate(self, stream: 'grpclib.server.Stream[book_pb2.Book, book_pb2.Book]') -> None:
        pass

    @abc.abstractmethod
    async def BookDetail(self, stream: 'grpclib.server.Stream[book_pb2.BookDetailRequest, book_pb2.Book]') -> None:
        pass

    @abc.abstractmethod
    async def BookDelete(self, stream: 'grpclib.server.Stream[book_pb2.BookDeleteRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BookUpdate(self, stream: 'grpclib.server.Stream[book_pb2.BookUpdateRequest, book_pb2.Book]') -> None:
        pass

    @abc.abstractmethod
    async def BookList(self, stream: 'grpclib.server.Stream[book_pb2.BookListRequest, book_pb2.BookListResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/book.BookService/BookCreate': grpclib.const.Handler(
                self.BookCreate,
                grpclib.const.Cardinality.UNARY_UNARY,
                book_pb2.Book,
                book_pb2.Book,
            ),
            '/book.BookService/BookDetail': grpclib.const.Handler(
                self.BookDetail,
                grpclib.const.Cardinality.UNARY_UNARY,
                book_pb2.BookDetailRequest,
                book_pb2.Book,
            ),
            '/book.BookService/BookDelete': grpclib.const.Handler(
                self.BookDelete,
                grpclib.const.Cardinality.UNARY_UNARY,
                book_pb2.BookDeleteRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/book.BookService/BookUpdate': grpclib.const.Handler(
                self.BookUpdate,
                grpclib.const.Cardinality.UNARY_UNARY,
                book_pb2.BookUpdateRequest,
                book_pb2.Book,
            ),
            '/book.BookService/BookList': grpclib.const.Handler(
                self.BookList,
                grpclib.const.Cardinality.UNARY_UNARY,
                book_pb2.BookListRequest,
                book_pb2.BookListResponse,
            ),
        }


class BookServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.BookCreate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/book.BookService/BookCreate',
            book_pb2.Book,
            book_pb2.Book,
        )
        self.BookDetail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/book.BookService/BookDetail',
            book_pb2.BookDetailRequest,
            book_pb2.Book,
        )
        self.BookDelete = grpclib.client.UnaryUnaryMethod(
            channel,
            '/book.BookService/BookDelete',
            book_pb2.BookDeleteRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.BookUpdate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/book.BookService/BookUpdate',
            book_pb2.BookUpdateRequest,
            book_pb2.Book,
        )
        self.BookList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/book.BookService/BookList',
            book_pb2.BookListRequest,
            book_pb2.BookListResponse,
        )
